server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: shopcart-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/shopcart
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration #src/main/resources/db/migration

jwt:
  base64-secret: XJvVeX4befworCdrEN8c0cEvg31ePhFO1zTIAvK8UfboZzmlS7A9cuWO5LKlVcfU7lJrR1WVJypseGylxREqBg
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 86400

logging:
  level:
    root: INFO
    com.shopcart: DEBUG
    org.springframework.security: DEBUG

# jackson:
#   serialization:
#     write-dates-as-timestamps: false
